### ISSUE TITLE
IWatchableVariableListFeature may need access to experiment results

### ISSUE THREAD

**Issue by gidili** [openworm/org.geppetto.core#76]
It used to be that recordings (results) where inside aspects, now they are at the experiment level but in case of [this implementation](https://github.com/openworm/org.geppetto.core/blob/datamanager/src/main/java/org/geppetto/core/simulator/RecordingVariableListFeature.java#L85) of the interface recordings are needed (as there is no other way to interrogate watchable variables if there's no simulator, we just have a recording). Since they are not at that level anymore, they are not found and it's not populating the simulation tree. 

I think we should pass results down to the [IWatchableVariableListFeature interface](https://github.com/openworm/org.geppetto.core/blob/bb23dfbbac4b70c46a79fef2cb1e33b48dbdf458/src/main/java/org/geppetto/core/features/IWatchableVariableListFeature.java). It is not unreasonable that we may want to get the list of watchable variables from whatever is in the recording (which is what I need and what was happening in the development branch) in other cases too.

For example, take a NeuroML recording with no simulator defined in the experiment, where would we get the watchable variables if not from the recording? And so on for SPH etc.

**Comment by gidili** [comment]
@jrmartin @tarelli @adrianq what do you guys think? I am currently blocked by the above, the way things changed makes it so without the change I suggest (or equivalent) whatever I was doing in the dev branch is not working in datamanager. Any better ideas?

I have the same identical problem on the [IVisualTreeFeature interface](https://github.com/openworm/org.geppetto.core/blob/bb23dfbbac4b70c46a79fef2cb1e33b48dbdf458/src/main/java/org/geppetto/core/features/IVisualTreeFeature.java) on [this implementation](https://github.com/openworm/org.geppetto.core/blob/datamanager/src/main/java/org/geppetto/core/simulator/services/ColladaVisualTreeFeature.java#L52) where visulization tree variables where being fished from the recording.

**Comment by jrmartin** [comment]
I spent some time  looking at possibility of adding resutls to Aspect's model wrapper as before, to avoid any changes to interface. Best I thought would be to add ModelWrapper with results to Aspect node before calling the feature, this will have to happen somewhere in RuntimeExperiment.java class. Otherwise, interface change sounds good as well.

**Comment by adrianq** [comment]
@gidili I am not sure if I fully understand your problem. If you are dealing with recordings it is because the simulation is done and we can assume the experiment is finished, right? If so you shouldn't be calling populate simulation tree but the simulation tree should be populate [here](https://github.com/openworm/org.geppetto.simulation/blob/datamanager/src/main/java/org/geppetto/simulation/RuntimeExperiment.java#L134-L150). I guess you don't have the aspect configurations with the watched variables for the recordings but what you have for sure is the experiment and maybe from there you can call a method like listWatchableVariables(AspectNode aspectNode, Experiment experiment). However I realise that you would still have the problem with the visualisation feature...

That said, I wouldn't move a comma without listening to @tarelli opinion ;)

**Comment by gidili** [comment]
@adrianq thanks - we had a chat with @tarelli and I was confused by the fact that we are calling populateSimulationTree in GeppettoManager.updateRuntimeTreesWithResults so I thought it was necessary, but the trees are actually populate already before that call so it would seem it is redundant (I tried commenting it out and everything works so I guess we should take it out). I just have to extend the "createVariables" stuff for the visualisation tree and it should be OK.

**Comment by tarelli** [comment]
Obsolete post instance type refactoring
